name: tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4, 8.5]
        laravel: ['12.*', '13.*']

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, json
          coverage: pcov

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=${{ matrix.laravel }}" --prefer-stable --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Grab PHPUnit major version
        id: phpunit_version
        run: echo "MAJOR_VERSION=$(vendor/bin/phpunit --version | grep --only-matching --max-count=1 --extended-regexp '\b[0-9]+\.[0-9]+' | cut -d '.' -f 1)" >> $GITHUB_OUTPUT

      - name: Execute tests (PHPUnit >= 10)
        if: '${{ fromJSON(steps.phpunit_version.outputs.MAJOR_VERSION) >= 10 }}'
        run: vendor/bin/phpunit --configuration=phpunit10.xml.dist
